name: Actualizador de P2P Binance

on:
  schedule:
    # Se corre cada 18 minutos para mantener el P2P fresco
    - cron: '*/18 9-23,0-4 * * *'
  workflow_dispatch: 

jobs:
  actualizar-p2p:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v2

      - name: Instalar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Instalar Dependencias
        run: pip install requests streamlit
      
      - name: Correr Script P2P
        run: python P2papp.py

      - name: Guardar cambios en el repo
        run: |
          git config --global user.name 'Robot-P2P'
          git config --global user.email 'robot-p2p@github.com'
          git add p2p.json
          git commit -m "P2P actualizado" || echo "No hay cambios"
          git push
